# ReadTheDocs configuration file for XRayLabTool
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      # Install system dependencies if needed
      - echo "Installing system dependencies..."
      - apt-get update
      - apt-get install -y graphviz pandoc  # For inheritance diagrams and format conversion
    pre_build:
      # Ensure we have the latest pip and build tools
      - pip install --upgrade pip setuptools wheel
    post_build:
      # Run documentation validation
      - echo "Running documentation validation..."
      - python -m sphinx -b linkcheck docs docs/_build/linkcheck || echo "Some links may be broken"
      - echo "Build completed successfully"

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Optional but recommended formats for download
formats:
  - pdf
  - epub
  - htmlzip

# Search configuration with enhanced ranking
search:
  ranking:
    # Boost user-facing content
    quickstart.html: 10
    installation.html: 8
    tutorials/: 5
    examples.html: 4
    cli_guide.html: 3
    howto/: 2
    faq.html: 1
    # Reduce API reference prominence in search
    api/: -1
  ignore:
    # Exclude certain patterns from search indexing
    - "_build"
    - "*.js"
    - "*.css"

# Social cards and preview configuration
# These help with link previews on social media
submodules:
  include: []

# Additional ReadTheDocs features are configured through the web interface
